# Generated by Django 2.2.5 on 2020-05-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200525_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='houseRule',
            new_name='house_rules',
        ),
    ]
